<?php
// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}
use Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController;
/*
 * Plugin Name: sofizpay-qr-woocommerce
 * Plugin URI: https://sofizpay.com
 * Description: QR Payments for WooCommerce allows customers to pay using their preferred e-wallets through a QR code generated by SOFIZPAY. 
 * Version: 1.0.0
 * Requires PHP: 7.2
 * Copyright: c 2024 EURL sofizpay
 
 */
// Add a custom meta box to the order edit screen
add_action('add_meta_boxes', 'qr_pay_gateway_add_meta_box');

function qr_pay_gateway_add_meta_box() {
	$screen = class_exists( '\Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController' ) && wc_get_container()->get( CustomOrdersTableController::class )->custom_orders_table_usage_is_enabled()
		? wc_get_page_screen_id( 'shop-order' )
		: 'shop_order';
	
    add_meta_box(
        'qr_pay_gateway_meta_box',
        __('QR Payment Gateway Information', 'qr-pay-gateway'),
        'qr_pay_gateway_meta_box_content',
        $screen,
		'side',
		'high'
    );
}

// Callback function to render the content of the meta box
function qr_pay_gateway_meta_box_content($order_id, $order) {
	
    // Retrieve the order using $order_id
   $order = wc_get_order($order_id);
	
	// Retrieve existing values from the order meta
    $payment_memo = $order->get_meta( 'payment_memo', true);

    // Output the HTML for the meta box
    ?>
<p>
    <label for="payment_memo"><?php _e('payment memo', 'qr-pay-gateway'); ?></label>
    <input type="text" id="payment_memo" name="payment_memo" value="<?php echo esc_attr($payment_memo); ?>" disabled>
</p>

<?php
}
?>