<?php
if (!defined('ABSPATH')) {
    exit;
}
/*
 * Plugin Name: sofizpay-qr-woocommerce
 * Plugin URI: https://sofizpay.com
 * Description: QR Payments for WooCommerce allows customers to pay using their preferred e-wallets through a QR code generated by SOFIZPAY. 
 * Version: 1.0.0
 * Requires PHP: 7.2
 * Copyright: c 2024 EURL sofizpay
 
 */
add_action('woocommerce_checkout_update_order_meta', 'qr_pay_gateway_update_order_meta', 10, 2);

function qr_pay_gateway_update_order_meta($order_id){
 
        // Check if the selected payment method is QR Payment Gateway
        if (empty($_POST['payment_method']) || $_POST['payment_method'] !== 'qr_pay_gateway') {
            return;
        }

        // Sanitize and save the Payment Full Name data
        if (isset($_POST['payment_memo']) && !empty($_POST['payment_memo'])) {
            $payment_memo = wc_clean(wp_unslash($_POST['payment_memo']));
            update_post_meta($order_id, 'payment_memo', $payment_memo);
        }

}


?>