<?php
if (!defined('ABSPATH')) {
    exit;
}
/*
 * Plugin Name: sofizpay-qr-woocommerce
 * Plugin URI: https://sofizpay.com
 * Description: QR Payments for WooCommerce allows customers to pay using their preferred e-wallets through a QR code generated by SOFIZPAY. 
 * Version: 1.0.0
 * Requires PHP: 7.2
 * Copyright: c 2024 EURL sofizpay
 
 */
add_action('woocommerce_checkout_update_order_meta', 'qr_pay_gateway_update_order_meta', 10, 2);

function qr_pay_gateway_update_order_meta($order_id, $order) {
    // Check if the selected payment method is QR Payment Gateway  
    if (empty($_POST['payment_method']) || $_POST['payment_method'] !== 'qr_pay_gateway') {
        return;
    }

    // Retrieve the order using $order_id
    $order = wc_get_order($order_id);

    // Make sure $order is an instance of WC_Order before proceeding
  	if (!is_a($order, 'WC_Order')) {
        return;
    }

    // Sanitize and save the Payment Full Name data
    if (isset($_POST['payment_memo']) && !empty($_POST['payment_memo'])) {
        $payment_memo = wc_clean(wp_unslash($_POST['payment_memo']));
        $order->update_meta_data('payment_memo', $payment_memo);
    }


    // Save the changes to the order
    $order->save();
}


?>